# Generated by Django 3.0.6 on 2020-05-14 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='discription',
            new_name='description',
        ),
    ]
